
spring:
  application:
    name: Shop_63

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
server:
  servlet:
    context-path: /api
key:
  access: ${KEY_ACCESS}
  refresh: ${KEY_REFRESH}